export const apps = [
  { id: "counter", title: "Counter", group: "reactive" },
  { id: "effects", title: "Split effects", group: "reactive" },
  { id: "form-binding", title: "Form binding", group: "reactive" },
  { id: "context-theme", title: "Context", group: "reactive" },
  { id: "async-profile", title: "Async memo", group: "async" },
  { id: "optimistic-save", title: "Optimistic action", group: "async" },
  { id: "reveal-feed", title: "Reveal feed", group: "async" },
  { id: "projection-filter", title: "Projection", group: "async" },
  { id: "show-switch", title: "Show / Switch", group: "control" },
  { id: "repeat-grid", title: "Repeat grid", group: "control" },
  { id: "nested-tree", title: "Nested tree", group: "control" },
  { id: "error-reset", title: "Error reset", group: "control" },
  { id: "todolist", title: "Todo list", group: "apps" },
  { id: "store-cart", title: "Store cart", group: "apps" },
  { id: "kanban", title: "Kanban board", group: "apps" },
  { id: "inbox", title: "Inbox", group: "apps" },
  { id: "marketplace", title: "Lil marketplace", group: "apps" },
  { id: "keyed", title: "Keyed table", group: "performance" },
  { id: "spreadsheet", title: "Spreadsheet", group: "performance" },
  { id: "svg-clock", title: "SVG clock", group: "visual" },
  { id: "portal-modal", title: "Portal modal", group: "visual" },
]
